#!/bin/sh
set -e

TARGET_FILE="/tmp/env-config.js"

echo "==> Preparing runtime environment variables for Vite + Nginx..."

# ============================================================
# 1. LOAD PHYSICAL .env FILE AS FALLBACK (if it exists in container)
# ============================================================
if [ -f /usr/share/nginx/html/.env ]; then
  echo "    Found physical .env file. Loading fallbacks..."
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      ''|\#*) continue ;;
    esac
    key=$(echo "$line" | cut -d '=' -f 1)
    value=$(echo "$line" | cut -d '=' -f 2-)
    if [ -z "$(eval echo \$$key)" ]; then
      export "$key=$value"
      echo "    [.env fallback] $key loaded from file"
    else
      echo "    [K8s injection] $key already set in Pod env, skipping .env"
    fi
  done < /usr/share/nginx/html/.env
else
  echo "    No physical .env file found. Using OS environment variables."
fi

# ============================================================
# 2. GENERATE /usr/share/nginx/html/env-config.js FOR BROWSER
# ============================================================
echo "==> Generating $TARGET_FILE..."

cat > "$TARGET_FILE" << EOF
// Auto-generated by docker-entrypoint.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
window.__ENV = {
  VITE_API_URL: "${VITE_API_URL:-}",
  VITE_VILLAGE_ID: "${VITE_VILLAGE_ID:-}",
  VITE_VILLAGE_NAME: "${VITE_VILLAGE_NAME:-}",
  VITE_DOMAIN_URL: "${VITE_DOMAIN_URL:-}",
  VITE_GMAPS_API_KEY: "${VITE_GMAPS_API_KEY:-}",
  VITE_GOOGLE_ANALYTICS_ID: "${VITE_GOOGLE_ANALYTICS_ID:-}",
  VITE_CHATBOT_ID: "${VITE_CHATBOT_ID:-}",
  VITE_CHATBOT_BASE_URL: "${VITE_CHATBOT_BASE_URL:-}",
};
EOF

echo "==> env-config.js successfully created at /tmp/env-config.js."
ln -sf /tmp/env-config.js /usr/share/nginx/html/env-config.js 2>/dev/null || true
echo "==> Starting Nginx..."

# ============================================================
# 3. EXECUTE MAIN COMMAND (nginx -g 'daemon off;')
# ============================================================
exec "$@"
